### PR TITLE
Expose the getCookie function

### PR DESCRIPTION
**Pull request by selbekk**
We have this API file, where we need to get an XSRF token from a cookie for each request. It's not a React component, so I can't use the hook to access the cookie.

For now I've just copied out the getCookie code into our own codebase, but it would be useful to export it from this package as well.

### CODE REVIEW

**Comment by tylerwolff** [comment]
@selbekk Thanks for this! If this is going to be merged could you also export `setCookie` to cover all cases? Then it will be totally flexible. Let me know what you think

**Comment by selbekk** [comment]
Yeah sure I don’t mind doing that 😊

**Comment by selbekk** [comment]
So in order to document the `setCookie` function, I had to change the documentation structure in the README a tiny bit.

**Comment by tylerwolff** [comment]
@selbekk awesome, this looks good. I will merge and release sometime later today. Thanks again!

**Comment by selbekk** [comment]
Courtesy bump :)

**Comment by tylerwolff** [comment]
done thanks! Making release now

**Pull request merged**
