### PR TITLE
feat: added servser-side rendering support

### PR DESCRIPTION
**Pull request by natterstefan**
## Feature

- I added server-side rendering support, which eventually resolves https://github.com/tylerwolff/useCookie/issues/10

### CODE REVIEW

**Comment by tylerwolff** [comment]
Thanks for doing this! I'll get a release out soon

**Comment by tylerwolff** [comment]
@natterstefan v1.2.0 was released! https://www.npmjs.com/package/react-use-cookie let me know if you run into any issues

**Comment by natterstefan** [comment]
I will, thanks @tylerwolff.

**Comment by chpio** [comment]
This is still broken! It does not evaluate to the same result on the server & browser, breaking reacts hydration. On the server this returns `initialValue`, on a browser it returns the content of the cookie, but it has to return `initialValue` as well.

**Comment by natterstefan** [comment]
Hi @chpio,

you are right, that would resolve that issue effectively. I don't know why I missed that in the first place. I should've known that. 🤦‍♂️

Will you create a PR for that, as I am not using this in my current project anymore.

**Comment by chpio** [comment]
hmm, i don't know, my change does not issue an update if another component sets the same cookie, see https://github.com/tylerwolff/useCookie/pull/15

**Pull request merged**
